# Generated by Django 5.1.6 on 2025-02-12 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0002_visitorrecord_store_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorrecord',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='visitorrecord',
            name='entry_time',
        ),
        migrations.RemoveField(
            model_name='visitorrecord',
            name='new_visitors',
        ),
        migrations.RemoveField(
            model_name='visitorrecord',
            name='returning_visitors',
        ),
        migrations.RemoveField(
            model_name='visitorrecord',
            name='total_visitors',
        ),
        migrations.AddField(
            model_name='visitorrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitorrecord',
            name='store_id',
            field=models.CharField(max_length=100),
        ),
    ]
